
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false


book:
  name: 互联网世界观
  author: 李善友
  isbn: ${random.uuid}
  description: ${book.name} ,这本书还不错哦.

server:
  tomcat:
    uri-encoding: UTF-8


